FROM rust:1.38.0

WORKDIR /usr/src/bot

COPY . .

# Export environment variables
ARG DISCORD_TOKEN
ENV DISCORD_TOKEN=$DISCORD_TOKEN

ARG POSTGRES_USER
ENV POSTGRES_USER=$DB_USER

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=$DB_PASSWORD

ARG POSTGRES_HOST
ENV POSTGRES_HOST=$POSTGRES_HOST

ARG POSTGRES_DATABASE
ENV POSTGRES_DATABASE=$POSTGRES_DATABASE

# Compile
RUN cargo install --path .

# Run the instance
CMD ["0x0bot"]
